const createdExchanges = [
    {
      id: "1",
      nombre: "Roberto Sanz Requena",
      centro: "Florida Universitaria",
      dificultad: "A1",
      alumnos: 12,
      idiomaDeseado: "English",
      idioma: "Spanish",
      imagen: "JuanPerezGomez.webp",
    },
    {
      id: "2",
      nombre: "María Rodríguez López",
      centro: "Berenguer Dalmau",
      dificultad: "A2",
      alumnos: 22,
      idiomaDeseado: "Spanish",
      idioma: "French",
      imagen: "MariaRodriguezLopez.webp",
    },
    {
      id: "3",
      nombre: "Carlos Fernández Martínez",
      centro: "Esteve Paluzie",
      dificultad: "C2",
      alumnos: 7,
      idiomaDeseado: "French",
      idioma: "Russian",
      imagen: "CarlosFernandezMartinez.webp",
    },
    {
      id: "4",
      nombre: "Ana Sánchez Ruiz",
      centro: "Penya Rotja",
      dificultad: "B2",
      alumnos: 16,
      idiomaDeseado: "German",
      idioma: "Greek",
      imagen: "AnaSanchezRuiz.webp",
    },
    {
      id: "5",
      nombre: "Maria Petra Lopez",
      centro: "Esteve Paluzie",
      dificultad: "C1",
      alumnos: 5,
      idiomaDeseado: "French",
      idioma: "Italian",
      imagen: "img2.jpg",
    },
    {
      id: "6",
      nombre: "Luis Carlos Garcia",
      centro: "Esteve Paluzie",
      dificultad: "B1",
      alumnos: 28,
      idiomaDeseado: "Russian",
      idioma: "Turkish",
      imagen: "AnaSanchezRuiz.webp",
    },
  ];
  
  export default createdExchanges;
  